[FEAT] #102 - 포스트뷰 Rx + MVVM 테이블뷰 구현
hongjunehuke/VelogOniOS pull request #123
Opened 2023-06-04 10:52 UTC by meltsplit

## 📌 Summary

이미 준혁이가 개발해준 부분이지만 직접 구현해보는 것이 나을것 같아
기존에 준혁이가 작업해줬던 것은 **`Deprecated_Posts`** 에 보관중이고  
새롭게 **`Posts`** 폴더에서 개발중입니다.

RX와 MVVM 으로 테이블뷰 구현하는 것에 의의를 뒀습니다!

추가로 Post 관련 파일 구조와 설계구조가 변경될 것 같습니당

**[기존 구조]**
`Post` 
ㄴ keywordPosts
ㄴ SubscribePosts

**[바꾸려는 구조]**
`Home`

`Posts` 
ㄴ 트렌트
ㄴ 팔로우
ㄴ 키워드 1
ㄴ 키워드 2

**[구조 변경 이유]**
1. 키워드가 추가됨에 따라 PostVCFactory가 PostVC를 키워드별로 찍어내면 홈뷰에서 찍어낸 PostVC를 추가되도록 구상 중.
2. 동일한 PostsVC와 PostsVM을 사용하지만 PostsViewModel에서 어떤 API를 요청하는지에 따라 트렌드, 팔로우, 키워드 보여줄지 결정하는 방식)으로 개발하려고 함.
3. 현재는 키워드 API로 보여주고 있음. <- 해당 API 에 대한 설명 필요함! 준혁아 도와죠!

## ✍️ Description

TableView 두가지 기능만 개발하였습니다.
1. tableView가 데이터를 화면에 띄우는 것.
2. tableView cell 선택시 Web뷰로 이동하는 것.

**추가로 개발해야할 기능.**
- 와피아이 로딩화면
- 무한 스크롤 (페이지네이션)
- 스크랩 기능

- 이슈 티켓 : #102 

## 🔥 Test
![postVC](https://github.com/hongjunehuke/VelogOniOS/assets/57269348/81f11654-7f3d-4e45-b18e-5a6bb368b0fd)

2023-06-04 11:31 UTC, meltsplit reviewed
PostVC <-> PostVM 중점적으로 봐주시면 감사하겠슴당

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/View/PostTableViewCell.swift
> +final class PostTableViewCell: BaseTableViewCell {
준혁이가 만든 KeywordTVC 파일 코드 내용만 복붙해서 새로 만들었어욥

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewController/PostsViewController.swift
> +final class PostsViewController: UIViewController {
앞으로 해당 뷰컨이 모든 게시글 관련 VC를 담당하면 좋지 않을까 하는 생각입니다.

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewController/PostsViewController.swift
> +    }()
TableView Delegate와 Datasource를 채택하지 않아 여기서 셀의 높이를 지정해줬습니다.

### 고민1: 유동적인 Cell 높이
기존 postTableView Cell의 높이는 

사진이 있을때: CellXLarge
글만 있을 때: 글자수에 따라 유동적 

Delegate없이 위처럼 유동적으로 Cell의 높이를 수정하려면 어떻게 해야할지 고민입니다.

### 고민 2: Cell의 CornerRadius 와 셀 사이의 간격
기존 TableView는 셀사이 간격이나 cell의 Round 처리를 **하지 않아도** 둥글게 되고 셀 사이의 간격이 유지 되던데
이게 TableView 스타일을 `.insetGrouped`로 처리해서 그런걸까요? 아니면 제가 해당 코드를 못찾은 걸까요?

제가 구현할 때에는 cornerRadius와 셀 사이의 간격이 제대로 보여지지 않아 코드 몇줄 더 쳐서 구현하였습니당.
`backgroundColor` = systemGray6 설정한 이유도 이전 뷰와 비슷해 보이기 위해 작성한 코드

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewController/PostsViewController.swift
> +    }
추후 Base 컨벤션에 따라 리팩할게용

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewController/PostsViewController.swift
> +
이렇게 코드 치니까 테이블뷰에 데이터가 나오던데 도대체 어떤 방식 나오는지 모르겠음 ㅋㅋ. 
이게 왜 되누..?

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +final class PostsViewModel {
ViewMode 토론 ㄱㄱ합시다

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +final class PostsViewModel {
일단 헷갈리지 않기 위해 Input과 Output 구조체로 감쌌음.
MateRuner와 SobokSobok 참고하였음.

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +    }
ViewWillAppear BaseVC에 있는 것으로 알고있음 추후 리팩 예정!

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +    }
scrapButtonDidTap 같은 경우 Cell에서 전달해야할 Event임. 해당 뷰모델 Input 이벤트 구조 뭐가 좋을까?

### 구조 1
PostCell이 PostVC에게 Delegate 패턴으로 이벤트 전달. 
PostVC가 본인이 소유하고있는 PostVM으로 이벤트 전달
(현재 바인딩 구조로 가능할까?)

### 구조 2
PostCell 생성시 PostVC가 본인이 소유하고 있는 PostVM 전달해줌.
PostCell도 뷰모델 소유중.
PostCell에서 PostVM과 Input 바인딩 진행.

### 구조 3
더 좋은 방법 있을까요?

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +    }
### posts
posts 는 TableView에 보여줄 데이터. 기존엔 GetTagResponse였지만 
결국엔 뿌려야할 데이터는 TagPostDtoList이기에 해당 배열 구조체로 변경함.

### post
사용자가 Cell 선택시 해당 post의 정보가 들어온다. 
post에 새로운 값이 들어올시 VC는 웹뷰로 넘긴다.
사용자가 셀을 누르지 않을 수도 있으니 초깃값이 없는 Publish로 설정.

Output을 위처럼 구현하는 거 맞낭?

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +final class PostsViewModel {
통일성을 위해 모든 VM에  Input, Output 구조체 만들어서 관리할지
아니면 Input, Output 구조체 없는 구조로 할지 얘기해보면 좋을듯

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +
이부분이 가장 의아한 부분.
disposed 안에 disposed있는 구조.

input안에 output이 있는 구조.. 이거 맞아?

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +            .disposed(by: disposeBag)
url 옵셔널 처리를 가드문으로 할지 고차함수로 할지 고민중.
난 가드문이 좋은데 rx쟁이들은 다 고차함수 쓰는 것 같아.

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Feature/Posts/ViewModel/PostsViewModel.swift
> +    }
요거 복붙해왔음!
설명해줘!

2023-06-04 11:31 UTC, meltsplit commented on VelogOnMobile/Global/Util/Factory/PostViewControllerFactory.swift
> +}
추후 팩토리패턴 구현예정

2023-06-05 08:07 UTC, hongjunehuke commented
<img width="270" alt="스크린샷 2023-06-05 오후 5 05 27" src="https://github.com/hongjunehuke/VelogOniOS/assets/83629193/c0e65c9a-82d3-4f6a-b2d5-fcad4dd1aa0d">

Deprecated_Posts 쪽 Keyword 폴더의 파일들을 현재 PR의 Posts 폴더의 파일들과 같은 기능을하고 있는것 같습니다! Keyword 폴더쪽 파일을 살리는 방향이 좋아보입니다. (Keyword 폴더쪽에 Realm 스크랩 기능과 API 연결까지 되어있어서요!)

2023-06-05 08:13 UTC, hongjunehuke commented
p1;
![Simulator Screen Recording - iPhone 14 Pro - 2023-06-05 at 17 11 48](https://github.com/hongjunehuke/VelogOniOS/assets/83629193/b1834dd4-2f89-471f-90c0-ce5f0a248baf)

우측 스와이프로 뷰를 이동한 이후, 탭바로 다른 뷰로 넘어갔다 다시 Post로 왔을 때 스와이프가 한 단계씩되지 않는것 같습니다!

2023-06-05 08:15 UTC, hongjunehuke requested changes

2023-06-05 08:36 UTC, hongjunehuke approved these changes

2023-06-20 13:11 UTC, closed without merging